### ISSUE TITLE
Webinar : Introduction to containers 

### ISSUE THREAD

**Issue by rowdymehul** [Internautsorg/technopanti-design#2]
## Goal: 
Introduction to Docker and Containers - Poster 

## Info: 
Need the poster design. 
Date: 16th May 2020
Time: 11.00 AM

## Style Information: 
Need the simple design with Title of the topic, Date & time, Hosting platform information. 

## Deadline: 
12th May 2020

## Tag: 
[Design Needed, Support Needed]

**Comment by mpokar** [comment]
![Frame 4](https://user-images.githubusercontent.com/49711004/81828254-39a48c80-9557-11ea-8901-a33e1568ebed.png)

Speaker Banner

**Comment by rowdymehul** [comment]
Thanks to @mpokar :)
