### ISSUE TITLE
Introduction to design in flutter

### ISSUE THREAD

**Issue by viveky259259** [Internautsorg/technopanti-design#3]
## Goal: 
Introduction to code generation in flutter by Adobe XD
[We will use xd designs to generate flutter code and use it in app]

## Info: 
It will be used for twitter and logo purposes

Need the poster design.
Date: 23 th May 2020
Time: 11.00 AM

## Style Information: 
something like this : https://twitter.com/technopanti/status/1260576541706240001

## Deadline: 
18th May 2020

## Tag: 
[Design Needed, Support Needed]

**Comment by rowdymehul** [comment]
@viveky259259 Can you share your picture?

**Comment by viveky259259** [comment]
Here it is https://photos.app.goo.gl/oaMqT2aJKDEUmkRe9

**Comment by viveky259259** [comment]
@rowdymehul  I have updated this issue Goal

**Comment by rowdymehul** [comment]
Noted @viveky259259

**Comment by mpokar** [comment]
![Vivek-yadav-flutter](https://user-images.githubusercontent.com/49711004/82101947-948edd00-972b-11ea-982a-6e6b81792a3a.png)
Done

**Comment by viveky259259** [comment]
It looks cool!!

**Comment by rowdymehul** [comment]
Thanks to @mpokar
