### ISSUE TITLE
Webinar 3: Event design 

### ISSUE THREAD

**Issue by rowdymehul** [Internautsorg/technopanti-design#4]
## Goal: 
Poster design needed for the event promotion. 

## Info: 
Talk Title: We are Building Dystopia using AI and ML 
Speaker Name: Viral Parmar 
Event Date : 30th May 2020
Time: 11.00 am to 12PM

## Style Information: 
Make sure it fits in the respective size as per the platforms. 

## Deadline: 
26th May 2020.

**Comment by mpokar** [comment]
Okay. Will submit design by today evening.

**Comment by mpokar** [comment]
![Viral-parmar](https://user-images.githubusercontent.com/49711004/82810863-24135900-9ead-11ea-810f-24fde4697fad.png)

Sample submit

**Comment by rowdymehul** [comment]
@mpokar 

Can you replace "Supported by" with "Initiative By".

**Comment by mpokar** [comment]
![VIRAL PARMAR](https://user-images.githubusercontent.com/49711004/82817128-0d273380-9eba-11ea-9008-e88d83068004.png)

Is it fine?

**Comment by rowdymehul** [comment]
Yes. Thanks @mpokar 👍

**Comment by viveky259259** [comment]
Yes
